framework:
  session:
    handler_id: session.handler.pdo
    cookie_secure: auto

services:
  session.pdo:
    class: PDO
    arguments:
      - '%env(resolve:DATABASE_URL)%'

  session.handler.pdo:
    class: Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler
    arguments:
      - '@session.pdo'
      - { db_table: sessions }
