# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters: 
    image_dir: '%kernel.project_dir%/public/uploads'
    avatar_dir: '%kernel.project_dir%/public/uploads/avatars'
    momo.partner_code: '%env(MOMO_PARTNER_CODE)%'
    momo.access_key:   '%env(MOMO_ACCESS_KEY)%'
    momo.secret_key:   '%env(MOMO_SECRET_KEY)%'
    momo.endpoint:     '%env(MOMO_ENDPOINT)%'
services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
    App\Service\MomoService:
        arguments:
            $partnerCode: '%env(string:MOMO_PARTNER_CODE)%'
            $accessKey: '%env(string:MOMO_ACCESS_KEY)%'
            $secretKey: '%env(string:MOMO_SECRET_KEY)%'
            $endpoint: '%env(string:MOMO_ENDPOINT_PAY)%'           
            $momoRefundEndpoint: '%env(string:MOMO_ENDPOINT_REFUND)%'
    App\Security\AccessDeniedHandler: ~
            # add more service definitions when explicit configuration is needed
            # please note that last definitions always *replace* previous ones
